### PR TITLE
bufferSrcCtx.Initialize with dictionary

### PR DESCRIPTION
**Pull request by oldma3095**
BuffersrcFilterContext.Initialize(d *Dictionary)
FilterGraph.NbFilters()
FilterGraph.Filters()
FilterContext.SetHardwareDeviceContext(hdc *HardwareDeviceContext)

### CODE REVIEW

**Comment by oldma3095** [comment]
image
fix hardware filter with `hwupload` `hwdownload`.
like this `filterGraph.Parse("movie=filename=logo.png,format=nv12,hwupload[movie0];[in][movie0]overlay_cuda=x=(W-w)/2+100:y=(H-h)/2+100[overlay0];[overlay0]scale_cuda=w=1080:h=720[out]", inputs, outputs)`

**Comment by asticode** [comment]
Can you make a different PR for 
```
FilterGraph.NbFilters()
FilterGraph.Filters()
FilterContext.SetHardwareDeviceContext(hdc *HardwareDeviceContext)
```
?

**Comment by oldma3095** [comment]
> Can you make a different PR for
> 
> ```
> FilterGraph.NbFilters()
> FilterGraph.Filters()
> FilterContext.SetHardwareDeviceContext(hdc *HardwareDeviceContext)
> ```
> 
> ?

ok

**Comment by asticode** [comment]
Thanks for the PR! ❤️

**Pull request merged**
