### PR TITLE
hardware filter

### PR DESCRIPTION
**Pull request by oldma3095**
BuffersrcFilterContext
BuffersrcFilterContext.SetBuffersrcParameters(*parameters)

BuffersrcParameters
AllocBuffersrcParameters()
BuffersrcParameters.HardwareFrameContext()
BuffersrcParameters.SetHardwareFrameContext(*hardwareFrameContext)

### CODE REVIEW

**Comment by oldma3095** [comment]
Just test hardware filter with cuda.
Tip: You must decode a frame , than you can get a non-nil hw_frame_ctx from decodeCtx

**Comment by oldma3095** [comment]
20e936ac759bffdb608d882169f56400

**Comment by asticode** [comment]
Thanks a lot for the PR!

Unfortunately, following [this comment](https://github.com/asticode/go-astiav/issues/112#issuecomment-2510597406), I was already working on adding the proper methods to allow using hardware filtering with `go-astiav` 😱 

Could you check out the `hardware-filtering` branch and let me know whether the new `hardware_decoding_filtering` works properly? And if new methods work properly with your workflow?

**Comment by oldma3095** [comment]
it can work by `hardware-filtering` branch.
cuda -> decode h264_cuvid -> encode h264_nvenc
vaapi -> h264 -> h264_vaapi

**Comment by asticode** [comment]
Did you also have time to test the `hardware_decoding_filtering` example?

**Pull request closed without merging**
